version: '3'

silent: true

tasks:

  patch:
    desc: Applies patches to original TCK repository
    cmds:
      - cmd: ./apply-patches.sh ../tck

  unpatch:
    desc: Removes patches from original TCK repository
    cmds:
      - cmd: ./remove-patches.sh ../tck
